#!/bin/bash

. ~/linuxenv/base/styles/setting

echo -e "$STAR Checking my favorites packages..."
if [ ! -f /usr/bin/aptitude ]; then
	sudo apt install -y aptitude
fi


if [ ! -f /usr/bin/vim ]; then
	sudo apt install -y vim
	sudo dnf install -y vim 
fi

if [ ! -f /usr/bin/nvim ]; then
	sudo apt install -y neovim
	sudo dnf install -y neovim
fi

if [ ! -f /usr/bin/tree ]; then
	sudo apt install -y tree
	sudo dnf install -y tree
fi
