#!/bin/bash
#
#-----  config de entorno de trabajo personal - Willians ppwj@yahoo.com   ---
#
#    Agregar esta linea  (if...fi) en:     .bashrc
# personal environment
#link_env() {
#   if [ ! -d ~/_myLinuxENV ]; then
#	   ln -s ~/linuxenv/_myLinuxENV ~/
#
#	   echo -e "$BULLET Environment linked!"
#   fi
#}
#
#if [ -f ~/linuxenv/_myLinuxENV/config/workshop ]; then
#
#	link_env
#
#   source  ~/linuxenv/_myLinuxENV/config/workshop
#   echo -e "$OK Personal Workshop/environment enabled"
#
#else
#      echo -e "$WARNING - Workshop is disabled, 'linuxenv' not found!"
#fi



# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac


. ~/_myLinuxENV/styles/setting 

# Directorio principal del entorno de trabajo para Docker
MSA="/msa"  # microservices environment

# Deployments  Docker
DEPLOY="/deployments"

# todos mis scripts para simplificar tareas
if [ -d "$HOME/_myscripts" ] ; then
    export PATH="$PATH:$HOME/_myscripts"
 fi

#if [ -d "$HOME/run" ] ; then
#   export PATH="$PATH:$HOME/run"
#fi



# lo mismo pero con algunos retoques
alias ll='clear && ls -lFh'
alias la='clear && ls -a'
alias l='clear && ls -lCFGh'
#alias vimg='vim.gtk'
#alias vi='nvim'
alias ..='cd ..'

# gestion rapida de containers, stop, start, remove
if [ -d "$DEPLOY/manage" ] ; then
   PATH="$PATH:$DEPLOY/manage"
fi

# mi area de trabajo docker
if [ -d "$MSA/cmt/" ] ; then
   PATH="$PATH:$MSA/cmt"
fi


#  entorno de Programacion Go
export PATH=$PATH:/usr/local/go/bin
export GOPATH="$HOME/Go_workspace"



# systemctl
alias sctlstatus='sudo systemctl "$@" status'
alias sctlstop='sudo systemctl "$@" stop'
alias sctlstart='sudo systemctl "$@" start'

# apt 
alias pkginstall='sudo aptitude install "$@"'
alias pkgreinstall='sudo aptitude reinstall'
alias pkgsearch='aptitude search "$@"'
alias pkgremove='sudo aptitude remove'
alias pkginfo='aptitude info'
alias pkgupdate='sudo aptitude update'


# Docker 
if [ -f /msa/cmt/deploy/complete-cms/addcms ]; then
   export PATH="$PATH:/msa/cmt/deploy/complete-cms/"
fi

# quick compare about this files laptop vs desktop/PC
cmd=$(md5sum ~/_myLinuxENV/config/workshop)
echo -e "$cmd"

# install my favs apps
~/_myLinuxENV/pkg/check_apps

# my scripts ready to use it
export PATH="$PATH:~/_myLinuxENV/scripts"

# enable .vimrc
if [ -f ~/.vimrc ]; then
   echo -e "$ASTERISK .vimrc esta enlazado"
else
   if [ -f ~/linuxenv/_myLinuxENV/config/vimrc ]; then
      ln -s ~/linuxenv/_myLinuxENV/config/vimrc .vimrc
      echo -e "$ASTERISK .vimrc ha sido configurado"
   else
      echo -e "$ALERT .vimrc no pudo ser activado, el archivo no existe"
   fi
fi


# vim setting 
link_vim() {
    if [ ! -f ~/.vim/vimrc ]; then
       ln -s ~/linuxenv/_myLinuxENV/config/vimrc ~/.vim/vimrc
        echo -e " .vim/vimrc enabled" 
    fi
}
link_autoload() {

    if [ ! -d ~/.vim/autoload ]; then
	ln -s ~/linuxenv/_myLinuxENV/config/autoload ~/.vim/autoload
        echo -e ".vim/autoload enabled" 
	
    fi
}
link_plugged() {
    if [ ! -d ~/.vim/plugged ]; then
	ln -s ~/linuxenv/_myLinuxENV/config/plugged ~/.vim/plugged
        echo -e ".vim/plugged enabled" 
    fi
}
link_all() {
   link_vim
   link_autoload
   link_plugged
   echo -e "All link checked"
}

if [ -d ~/.vim ]; then
   link_all
else
   echo -e "$ALERT Directorio $YELLOW .vim $RST no existe."
   mkdir -p .vim
   echo -e "$ASTERISK Dir .vim creado!"
   link_all
fi
#--- end vim setup


# enable .config/nvim/init.vim
link_initvim() {
   ln -s ~/linuxenv/_myLinuxENV/config/init.vim ~/.config/nvim/init.vim
}
if [ -f ~/.config/nvim/init.vim ]; then
   echo -e "$ASTERISK init.vim esta enlazado"
else
   # does init.vim exist?
   if [ -f ~/linuxenv/_myLinuxENV/config/init.vim ]; then
      # does the config dir exist? 
      if [ -d ~/.config/nvim ]; then

         link_initvim

      else 
         echo -e "$ALERT El directorio $YELLOW .config/nvim$RST no existe, ¡creado!"
         mkdir -p ~/.config/nvim

	link_initvim

      fi
      
         echo -e "$ASTERISK .config/nvim/init.vim ha sido configurado"

   else

      echo -e "$ALERT init.vim no pudo ser activado, el archivo no existe"

   fi
fi

# prompt
export PS1="\H \t [ \[\e[36;40m\]\w\[\e[m\] ] >  "
export PS1='\[\e[0m\]\t\[\e[m\] \[\e[0m\](\[\e[0;1;38;5;46m\]$(ip route get 1.1.1.1 | awk -F"src " '"'"'NR==1{split($2,a," ");print a[1]}'"'"')\[\e[0m\])\[\e[m\] \[\e[0;38;5;46m\]\w\[\e[m\] \[\e[0m\]\$\[\e[m\] \[\e0'

PS1='\[\e[0m\][\[\e[0;38;5;47m\]$(ip route get 1.1.1.1 | awk -F"src " '"'"'NR==1{split($2,a," ");print a[1]}'"'"')\[\e[0m\]]\[\e[m\] \[\e[0m\]\t\[\e[m\] \[\e[0;38;5;76m\]\u\[\e[m\] \[\e[0;1;7;38;5;40;48;5;232m\]\w\[\e[m\] \[\e[0m\](\[\e[0m\]\j\[\e[0m\])\[\e[m\] \[\e[0m\]$(git branch 2>/dev/null | grep '"'"'^*'"'"' | colrm 1 2)\[\e[m\] \[\e[m\]\n\[\e[0m\]$ '

